import type { ComponentDefinition } from "./types";

// Okta brand blue used for all Okta-native components
const OKTA = "#007DC1";

export const COMPONENT_REGISTRY: ComponentDefinition[] = [
  // ── Users & Devices ──────────────────────────────────────────────────────
  {
    id: "end-user",
    label: "End User",
    category: "users-devices",
    fallbackMonogram: "U",
    color: "#4F46E5",
    nodeType: "user-device",
  },
  {
    id: "admin-user",
    label: "Administrator",
    category: "users-devices",
    fallbackMonogram: "ADM",
    color: "#4F46E5",
    nodeType: "user-device",
  },
  {
    id: "guest-user",
    label: "Guest / External User",
    category: "users-devices",
    fallbackMonogram: "GST",
    color: "#4F46E5",
    nodeType: "user-device",
  },
  {
    id: "nhi",
    label: "Non-Human Identity",
    category: "users-devices",
    fallbackMonogram: "NHI",
    color: "#4F46E5",
    nodeType: "user-device",
  },
  {
    id: "managed-device",
    label: "Managed Device",
    category: "users-devices",
    fallbackMonogram: "MDV",
    color: "#4F46E5",
    nodeType: "user-device",
  },
  {
    id: "unmanaged-device",
    label: "Unmanaged Device",
    category: "users-devices",
    fallbackMonogram: "UDV",
    color: "#4F46E5",
    nodeType: "user-device",
  },
  {
    id: "mobile-device",
    label: "Mobile Device",
    category: "users-devices",
    fallbackMonogram: "MOB",
    color: "#4F46E5",
    nodeType: "user-device",
  },
  {
    id: "desktop",
    label: "Desktop / Workstation",
    category: "users-devices",
    fallbackMonogram: "DKT",
    color: "#4F46E5",
    nodeType: "user-device",
  },

  // ── Resources ───────────────────────────────────────────────────────────
  {
    id: "oin-application",
    label: "OIN Application",
    category: "resources",
    fallbackMonogram: "OIN",
    color: "#059669",
    nodeType: "resource",
  },
  {
    id: "custom-application",
    label: "Custom Application",
    category: "resources",
    fallbackMonogram: "APP",
    color: "#059669",
    nodeType: "resource",
  },
  {
    id: "api-endpoint",
    label: "API Endpoint",
    category: "resources",
    fallbackMonogram: "API",
    color: "#059669",
    nodeType: "resource",
  },
  {
    id: "saml-application",
    label: "SAML Application",
    category: "resources",
    fallbackMonogram: "SAML",
    color: "#059669",
    nodeType: "resource",
  },
  {
    id: "oidc-application",
    label: "OIDC Application",
    category: "resources",
    fallbackMonogram: "OIDC",
    color: "#059669",
    nodeType: "resource",
  },

  // ── Customer (config-driven, not in sidebar) ────────────────────────────
  {
    id: "customer",
    label: "Customer",
    category: "customer",
    lucideIcon: "building-2",
    fallbackMonogram: "C",
    color: "#475569",
    nodeType: "customer",
  },

  // ── Core Identity ────────────────────────────────────────────────────────
  {
    id: "universal-directory",
    label: "Universal Directory",
    category: "core-identity",
    fallbackMonogram: "UD",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "identity-engine",
    label: "Identity Engine",
    category: "core-identity",
    fallbackMonogram: "OIE",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "sso",
    label: "Single Sign-On (SSO)",
    category: "core-identity",
    fallbackMonogram: "SSO",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "adaptive-mfa",
    label: "Adaptive MFA",
    category: "core-identity",
    fallbackMonogram: "MFA",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "okta-verify",
    label: "Okta Verify",
    category: "core-identity",
    fallbackMonogram: "OV",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "lifecycle-management",
    label: "Lifecycle Management",
    category: "core-identity",
    fallbackMonogram: "LCM",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "api-access-management",
    label: "API Access Management",
    category: "core-identity",
    fallbackMonogram: "AAM",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "authorization-server",
    label: "Authorization Server",
    category: "core-identity",
    fallbackMonogram: "AS",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "workflows",
    label: "Okta Workflows",
    category: "core-identity",
    fallbackMonogram: "WF",
    color: OKTA,
    nodeType: "okta-component",
  },

  // ── Customer Identity (CIAM / Auth0) ────────────────────────────────────
  {
    id: "cic",
    label: "Customer Identity Cloud",
    category: "customer-identity",
    fallbackMonogram: "CIC",
    color: "#EB5424",
    nodeType: "okta-component",
  },
  {
    id: "universal-login",
    label: "Universal Login",
    category: "customer-identity",
    fallbackMonogram: "UL",
    color: "#EB5424",
    nodeType: "okta-component",
  },
  {
    id: "passwordless",
    label: "Passwordless",
    category: "customer-identity",
    fallbackMonogram: "PWL",
    color: "#EB5424",
    nodeType: "okta-component",
  },
  {
    id: "social-connections",
    label: "Social Connections",
    category: "customer-identity",
    fallbackMonogram: "SC",
    color: "#EB5424",
    nodeType: "okta-component",
  },
  {
    id: "b2c-flows",
    label: "B2C Flows",
    category: "customer-identity",
    fallbackMonogram: "B2C",
    color: "#EB5424",
    nodeType: "okta-component",
  },
  {
    id: "b2b-flows",
    label: "B2B Flows",
    category: "customer-identity",
    fallbackMonogram: "B2B",
    color: "#EB5424",
    nodeType: "okta-component",
  },
  {
    id: "actions",
    label: "Actions",
    category: "customer-identity",
    fallbackMonogram: "ACT",
    color: "#EB5424",
    nodeType: "okta-component",
  },
  {
    id: "fine-grained-authz",
    label: "Fine-Grained Authorization",
    category: "customer-identity",
    fallbackMonogram: "FGA",
    color: "#EB5424",
    nodeType: "okta-component",
  },

  // ── Workforce Identity ────────────────────────────────────────────────────
  {
    id: "access-gateway",
    label: "Okta Access Gateway",
    category: "workforce",
    fallbackMonogram: "OAG",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "fastpass",
    label: "FastPass",
    category: "workforce",
    fallbackMonogram: "FP",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "device-trust",
    label: "Device Trust",
    category: "workforce",
    fallbackMonogram: "DT",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "desktop-mfa",
    label: "Desktop MFA",
    category: "workforce",
    fallbackMonogram: "DMFA",
    color: OKTA,
    nodeType: "okta-component",
  },
  {
    id: "radius",
    label: "RADIUS",
    category: "workforce",
    fallbackMonogram: "RAD",
    color: OKTA,
    nodeType: "okta-component",
  },

  // ── Privileged Access (OPA) ───────────────────────────────────────────────
  {
    id: "opa",
    label: "Okta Privileged Access",
    category: "privileged-access",
    fallbackMonogram: "OPA",
    color: "#7C3AED",
    nodeType: "okta-component",
  },
  {
    id: "jit-access",
    label: "Just-in-Time Access",
    category: "privileged-access",
    fallbackMonogram: "JIT",
    color: "#7C3AED",
    nodeType: "okta-component",
  },
  {
    id: "secrets-vault",
    label: "Secrets Vault",
    category: "privileged-access",
    fallbackMonogram: "SVT",
    color: "#7C3AED",
    nodeType: "okta-component",
  },
  {
    id: "session-recording",
    label: "Session Recording",
    category: "privileged-access",
    fallbackMonogram: "SR",
    color: "#7C3AED",
    nodeType: "okta-component",
  },
  {
    id: "credential-vaulting",
    label: "Credential Vaulting",
    category: "privileged-access",
    fallbackMonogram: "CV",
    color: "#7C3AED",
    nodeType: "okta-component",
  },
  {
    id: "privilege-elevation",
    label: "Privilege Elevation",
    category: "privileged-access",
    fallbackMonogram: "PE",
    color: "#7C3AED",
    nodeType: "okta-component",
  },
  {
    id: "server-access",
    label: "Advanced Server Access",
    category: "privileged-access",
    fallbackMonogram: "ASA",
    color: "#7C3AED",
    nodeType: "okta-component",
  },

  // ── Identity Governance (OIG) ─────────────────────────────────────────────
  {
    id: "oig",
    label: "Identity Governance",
    category: "governance",
    fallbackMonogram: "OIG",
    color: "#0F766E",
    nodeType: "okta-component",
  },
  {
    id: "access-requests",
    label: "Access Requests",
    category: "governance",
    fallbackMonogram: "AR",
    color: "#0F766E",
    nodeType: "okta-component",
  },
  {
    id: "access-certifications",
    label: "Access Certifications",
    category: "governance",
    fallbackMonogram: "AC",
    color: "#0F766E",
    nodeType: "okta-component",
  },
  {
    id: "entitlement-management",
    label: "Entitlement Management",
    category: "governance",
    fallbackMonogram: "EM",
    color: "#0F766E",
    nodeType: "okta-component",
  },
  {
    id: "separation-of-duties",
    label: "Separation of Duties",
    category: "governance",
    fallbackMonogram: "SoD",
    color: "#0F766E",
    nodeType: "okta-component",
  },
  {
    id: "identity-analytics",
    label: "Identity Analytics",
    category: "governance",
    fallbackMonogram: "IA",
    color: "#0F766E",
    nodeType: "okta-component",
  },

  // ── Integrations & Platform ────────────────────────────────────────────────
  {
    id: "oin",
    label: "Okta Integration Network",
    category: "integrations",
    fallbackMonogram: "OIN",
    color: "#0EA5E9",
    nodeType: "okta-component",
  },
  {
    id: "scim",
    label: "SCIM Provisioning",
    category: "integrations",
    fallbackMonogram: "SCIM",
    color: "#0EA5E9",
    nodeType: "okta-component",
  },
  {
    id: "saml",
    label: "SAML 2.0",
    category: "integrations",
    fallbackMonogram: "SAML",
    color: "#0EA5E9",
    nodeType: "okta-component",
  },
  {
    id: "oidc",
    label: "OpenID Connect",
    category: "integrations",
    fallbackMonogram: "OIDC",
    color: "#0EA5E9",
    nodeType: "okta-component",
  },
  {
    id: "inbound-federation",
    label: "Inbound Federation",
    category: "integrations",
    fallbackMonogram: "IBF",
    color: "#0EA5E9",
    nodeType: "okta-component",
  },
  {
    id: "outbound-federation",
    label: "Outbound Federation",
    category: "integrations",
    fallbackMonogram: "OBF",
    color: "#0EA5E9",
    nodeType: "okta-component",
  },
  {
    id: "event-hooks",
    label: "Event Hooks",
    category: "integrations",
    fallbackMonogram: "EH",
    color: "#0EA5E9",
    nodeType: "okta-component",
  },
  {
    id: "inline-hooks",
    label: "Inline Hooks",
    category: "integrations",
    fallbackMonogram: "IH",
    color: "#0EA5E9",
    nodeType: "okta-component",
  },
  {
    id: "log-streaming",
    label: "Log Streaming",
    category: "integrations",
    fallbackMonogram: "LS",
    color: "#0EA5E9",
    nodeType: "okta-component",
  },

  // ── Security & Threat ──────────────────────────────────────────────────────
  {
    id: "threatinsight",
    label: "ThreatInsight",
    category: "security",
    fallbackMonogram: "TI",
    color: "#DC2626",
    nodeType: "okta-component",
  },
  {
    id: "behavior-detection",
    label: "Behavior Detection",
    category: "security",
    fallbackMonogram: "BD",
    color: "#DC2626",
    nodeType: "okta-component",
  },
  {
    id: "phishing-resistance",
    label: "Phishing Resistance",
    category: "security",
    fallbackMonogram: "PR",
    color: "#DC2626",
    nodeType: "okta-component",
  },
  {
    id: "caep",
    label: "Continuous Access Eval (CAEP)",
    category: "security",
    fallbackMonogram: "CAEP",
    color: "#DC2626",
    nodeType: "okta-component",
  },
  {
    id: "entity-risk-policy",
    label: "Entity Risk Policy",
    category: "security",
    fallbackMonogram: "ERP",
    color: "#DC2626",
    nodeType: "okta-component",
  },
  {
    id: "identity-risk",
    label: "Identity Risk Scoring",
    category: "security",
    fallbackMonogram: "IRS",
    color: "#DC2626",
    nodeType: "okta-component",
  },

  // ── Singleton central node ─────────────────────────────────────────────────
  {
    id: "okta-logo",
    label: "Okta",
    category: "okta-logo",
    fallbackMonogram: "OKTA",
    color: OKTA,
    nodeType: "okta-logo",
  },
];

const BY_ID = new Map(COMPONENT_REGISTRY.map((c) => [c.id, c]));

export function getComponentDefinition(
  id: string,
): ComponentDefinition | undefined {
  return BY_ID.get(id);
}

export function getSidebarComponents(): ComponentDefinition[] {
  return COMPONENT_REGISTRY.filter(
    (c) => c.category !== "okta-logo" && c.category !== "customer",
  );
}
